name: Sync GitHub to Gitee

on:
  workflow_dispatch:
  schedule:
    # At minute 20 past every 4th hour.
    - cron: "20 */4 * * *"

jobs:
  sync-repos:
    runs-on: windows-latest
    env:
      USER_NAME: "abgox"
      USER_EMAIL: "abgohxf@outlook.com"
    steps:
      - name: Setup SSH
        shell: pwsh
        env:
          SSH_CONFIG: ${{ secrets.SSH_CONFIG }}
          SSH_ID_RSA_GITHUB: ${{ secrets.SSH_ID_RSA_GITHUB }}
          SSH_ID_RSA_GITEE: ${{ secrets.SSH_ID_RSA_GITEE }}
        run: |
          # Create secure directory
          $sshDir = "$HOME\.ssh"
          New-Item -Path $sshDir -ItemType Directory -Force
          attrib +h $sshDir

          # Write key files
          $env:SSH_CONFIG | Out-File "$sshDir\config" -Encoding utf8NoBOM
          $env:SSH_ID_RSA_GITHUB | Out-File "$sshDir\id_rsa_github" -Encoding utf8NoBOM
          $env:SSH_ID_RSA_GITEE | Out-File "$sshDir\id_rsa_gitee" -Encoding utf8NoBOM

          # Set strict permissions
          icacls "$sshDir\id_rsa_github" /reset /grant:r "$env:USERNAME`:F" /inheritance:r
          icacls "$sshDir\id_rsa_gitee" /reset /grant:r "$env:USERNAME`:F" /inheritance:r

          # Add host fingerprints to known_hosts
          ssh-keyscan github.com gitee.com >> "$sshDir\known_hosts"

      - name: Configure Git
        shell: pwsh
        run: |
          git config --global user.name $env:USER_NAME
          git config --global user.email $env:USER_EMAIL

      - name: Verify SSH
        shell: pwsh
        run: |
          # ssh -T git@github.com
          ssh -T git@gitee.com

      - name: Sync Repos
        shell: pwsh
        run: |
          .\scripts\sync-github-to-gitee.ps1

      - name: Cleanup SSH
        if: always()
        shell: pwsh
        run: |
          Remove-Item "$HOME\.ssh" -Recurse -Force -ErrorAction SilentlyContinue
